log:
  exp_name: neti-2
  exp_dir: /content/NeTI/experiments
  save_steps: 250
  report_to: comet_ml
data:
  train_data_dir: /content/NeTI/syn_rgb
  placeholder_token: <*>
  super_category_token: side
  dataloader_num_workers: 2
model:
  pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
  use_nested_dropout: True
  nested_dropout_prob: 0.5
  normalize_mapper_output: True
  use_positional_encoding: True
  pe_sigmas: {'sigma_t': 0.03, 'sigma_l': 2.0, 'sigma_az': 0.03, 'sigma_el': 0.03}
  num_pe_time_anchors: 100
  output_bypass: True
  use_vps_encoder: True
  use_xformers: False
eval:
  validation_steps: 250
optim:
  max_train_steps: 1000
  learning_rate: 1e-3
  train_batch_size: 1
  gradient_accumulation_steps: 8
