# https://taskfile.dev

version: '3'

tasks:
  train:
    cmds:
      - COMET_API_KEY="MvZFPCkt1CN1iqrnsgahJ2Rwa" python scripts/train.py --config_path input_configs/train.yaml
  
  git-config:
    cmds:
      - git config user.email "sagiahrac@mail.tau.ac.il"
      - git config user.name "sagi ahrac"
  
  install-vscode-extensions:
    cmds:
      - code --install-extension ms-python.python
      - code --install-extension ms-python.vscode-pylance
      - code --install-extension github.copilot
      - code --install-extension ms-toolsai.jupyter
      - code --install-extension ms-vscode.cpptools
      - code --install-extension cameron.vscode-pytest
      - code --install-extension mhutchie.git-graph
      - code --install-extension donjayamanne.githistory
      - code --install-extension eamodio.gitlens
      - code --install-extension task.vscode-task
      - code --install-extension shd101wyy.markdown-preview-enhanced
  
  get-data:
    cmds:
      - cp /content/drive/MyDrive/research/rendered_100.zip .
      - unzip -q rendered_100.zip
  
  create-env:
    cmds:
      - mamba env create -f environment/environment.yaml
  
  setup:
    cmds:
      - echo "Building NeTI dev env"
      - task: create-env
      - mamba install -n neti -c anaconda -c conda-forge -c comet_ml comet_ml
      - echo "Configuring GIT user"
      - task: git-config
      - echo "Getting VSCode extensions"
      - task: install-vscode-extensions
      - echo "Copy train data from drive"
      - task: get-data